# Generated by Django 2.0.2 on 2019-01-23 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('middlename', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('lastname', models.CharField(max_length=40, verbose_name='Segundo apellido')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Género')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(max_length=80, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo electrónico')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name', 'birthday', 'registered', 'updated', 'gender'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('content', models.TextField(max_length=400, verbose_name='Contenido')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('valoration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Valoración')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestion_clientes.Customer', verbose_name='Escrito por')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'ordering': ('title', 'published', 'edited', 'valoration'),
            },
        ),
    ]
