# Generated by Django 2.0.2 on 2019-01-23 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_restaurante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(through='gestion_restaurante.Order', to='gestion_restaurante.Product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
