# Generated by Django 2.0.2 on 2018-12-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_auto_20181219_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=400, verbose_name='Contenido'),
        ),
    ]
