# Generated by Django 2.0.2 on 2019-01-23 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_auto_20190123_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
