# Generated by Django 2.0.2 on 2019-01-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_auto_20190121_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
