# Generated by Django 2.0.2 on 2019-01-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0003_auto_20190123_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
