# Generated by Django 2.0.2 on 2019-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0010_auto_20190126_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(help_text='¿En qué día nació?', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Seleccione su sexo', max_length=1, verbose_name='Género'),
        ),
    ]
