# Generated by Django 2.0.2 on 2019-01-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0011_auto_20190126_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, help_text='¿En qué día nació?', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
