# Generated by Django 2.0.2 on 2019-01-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0013_auto_20190127_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestion_clientes.Customer', verbose_name='Escrito por'),
        ),
    ]
