# Generated by Django 2.0.2 on 2019-02-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0010_auto_20190206_2320'),
        ('gestion_clientes', '0015_auto_20190128_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(through='gestion_restaurante.Order', to='gestion_restaurante.Product', verbose_name='Productos'),
        ),
    ]
