# Generated by Django 2.0.2 on 2019-01-21 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comment', models.CharField(max_length=150, verbose_name='Comentario')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerOrders', to='gestion_clientes.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, verbose_name='Dirección')),
                ('zipCode', models.IntegerField(blank=True, null=True, verbose_name='Código postal')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ('address', 'city', 'country', 'zipCode'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Producto')),
                ('description', models.TextField(max_length=80, verbose_name='Descripción')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Unidades')),
                ('weigth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.DecimalValidator], verbose_name='Peso')),
                ('purchasers', models.ManyToManyField(through='gestion_restaurante.Order', to='gestion_clientes.Customer')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion_restaurante.Place', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productOrders', to='gestion_restaurante.Product', verbose_name='Productos'),
        ),
    ]
