# Generated by Django 2.0.2 on 2019-01-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, verbose_name='Dirección')),
                ('zipCode', models.IntegerField(blank=True, null=True, verbose_name='Código postal')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ('address', 'city', 'country', 'zipCode'),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_restaurante.Place', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ('name',),
            },
        ),
    ]
