# Generated by Django 2.0.2 on 2019-01-23 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='built',
            field=models.DateField(verbose_name='Contruido el '),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aforo'),
            preserve_default=False,
        ),
    ]
