# Generated by Django 2.0.2 on 2019-01-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'stock', 'weigth', 'created', 'updated'), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('name', 'built', 'capacity'), 'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchasers',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productOrder', to='gestion_restaurante.Product', verbose_name='Productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fabricado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='built',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Contruido el '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aforo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerOrder', to='gestion_clientes.Customer', verbose_name='Cliente'),
        ),
    ]
