# Generated by Django 2.0.2 on 2019-01-28 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0005_auto_20190128_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'created', 'updated'), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weigth',
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unidades'),
        ),
        migrations.AddField(
            model_name='order',
            name='weigth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso'),
        ),
    ]
