# Generated by Django 2.0.2 on 2019-01-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0006_auto_20190128_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.BigIntegerField(default=None, editable=False, verbose_name='ID Referencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=120, verbose_name='Descripción'),
        ),
    ]
