# Generated by Django 2.0.2 on 2019-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0007_auto_20190129_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentario'),
        ),
    ]
