# Generated by Django 2.0.2 on 2019-01-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0008_auto_20190129_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date', 'product', 'customer', 'stock', 'weigth'), 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
