# Generated by Django 2.0.2 on 2019-02-06 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_restaurante', '0009_auto_20190129_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='El valor mínimo es de 1.'), django.core.validators.MaxValueValidator(99999, message='No más de 5 cifras')], verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Descripción'),
        ),
    ]
